# ░░░░░░░░░░░░░░░   EntityPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/entityplus.70592/
#  Wiki: https://github.com/momoservertw/EntityPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 1

Entities:
  Default:
    Enable: false
    Priority: 0
    Drop:
      - lucky1
      - lucky2
    Damage:
      - Skip-Duration
      - Fast-Kill
      - Fast-Kill-WitherRose