name: EntityPlus
main: tw.momocraft.entityplus.EntityPlus
author: Momocraft
api-version: 1.14
version: 1.1.0
description: Control entities.
softdepend: [Vault, MythicMobs, CMI]

commands:
  entityplus:
    description: Displays main command menu.
    permission: entityplus.use
    usage: |
      /entityplus
  entityplus reload:
    description: Reloads all EntityPlus configuration files and caches any new data.
    permission: entityplus.reload
    usage: |
        /entityplus reload

permissions:
  entityplus.*:
    description: Allows use of all commands and feature.
    default: op
  entityplus.all:
    description: Allows use of all commands and feature.
    default: op
    children:
      entityplus.use: true
      entityplus.reload: true
      entityplus.bypass.spawnlimit.afk: true
      entityplus.bypass.purge.afk: true
  entityplus.use:
    description: Allows use of basic commands.
    default: true
  entityplus.reload:
    description: Allows use of /entityplus reload command.
    default: op
  entityplus.bypass.spawnlimit.afk:
    description: Bypass the spawn amount limit when player is afk.
    default: op
  entityplus.bypass.purge.afk:
    description: Bypass the purge event when player is afk.
    default: op