# --{ =-=-=-=-=-=-=-=-=-= EntityPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
Config-Version: 4
Log-Coloration: true
Debugging: false

General:
  # Please set the same value from your Spigot.yml. It will change the checking range of monsters.
  mob-spawn-range: 3

Purge:
  # Need plugin: CMI
  # It will automatic purging all creatures in the AFK list which near afk players every 30 minutes.
  AFK-Auto-Clean:
    Enable: false
    Interval: 30
  # If the player enters AFK, those entities near him will be check and purge.
  # Bypass permission: entityplus.bypass.purge.afk
  AFK:
    Enable: false
    # The chance of each creature will be purged. Set "1" to purge all creatures.
    Chance: 1
    Ignore:
      Named: true
      Tamed: true
      With-Saddle: true
      Baby-Animals: false
      Equipped: false
      Pickup-Equipped: true
      # Ignore spawn reason like "NATURAL" and "SPAWNER".
      # Spawn reason: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
      Reasons: []
      Worlds: []
    # Checking the purge list. If you set this option to false, it will purge every creatures.
    List-Enable: true
    List:
      - ZOMBIE
      - ZOMBIE_VILLAGER
      - SKELETON
      - CREEPER
      - SPIDER
      - WITCH
      - ENDERMAN
      - CAVE_SPIDER
      - SLIME
      - SILVERFISH
      - PIG_ZOMBIE
      - BLAZE
      - WITHER_SKELETON
      - MAGMA_CUBE
      - GHAST
      - STRAY
      - HUSK
      - DROWNED
      - PHANTOM
      - PILLAGER
      - RAVAGER
  MythicMobs-AFK:
    Enable: false
    Chance: 1
    Ignore:
      Named: true
      Tamed: true
      With-Saddle: true
      Baby-Animals: false
      Equipped: false
      Pickup-Equipped: true
      Worlds: []
    List-Enable: true
    List: []

Spawn-Limit:
  # If there are too many creatures over the spawn location, it will cancel the spawn event.
  # This setting can avoid the bug of spawn MythicMobs without limit when you are using "RandomRespawn".
  Range:
    Enable: false
    # The maximum amount near the player. You can set "-1" to disable this feature.
    Max-Amount: 5
    # The chance of each creature will be spawned. Set "0" to disable all creatures spawn.
    Chance: 0
    # The checking range near the spawn creature.
    Range:
      X: 8
      Y: 5
      Z: 8
    Ignore-Reasons: []
    Ignore-Worlds: []
    List-Enable: true
    List:
      - ZOMBIE
      - ZOMBIE_VILLAGER
      - SKELETON
      - CREEPER
      - SPIDER
      - WITCH
      - ENDERMAN
      - CAVE_SPIDER
      - SLIME
      - SILVERFISH
      - PIG_ZOMBIE
      - BLAZE
      - WITHER_SKELETON
      - MAGMA_CUBE
      - GHAST
      - STRAY
      - HUSK
      - DROWNED
      - PHANTOM
      - PILLAGER
      - RAVAGER
      - ILLUSIONER
      - VINDICATOR
      - EVOKER
      - VEX
      - VILLAGER
      - IRON_GOLEM
    # The creature will not be count in Max-Amount.
    Ignore-List: []
    MythicMobs-List-Enable: true
    MythicMobs-List: []
    MythicMobs-Ignore-List: []
  # Need plugin: CMI
  # If player is AFK, the entity will decrease spawning creatures.
  # Bypass permission: entityplus.bypass.spawnlimit.afk
  AFK:
    Enable: false
    Max-Amount: -1
    Chance: 0
    Ignore-Reasons: []
    Ignore-Worlds: []
    List-Enable: true
    List:
      - ZOMBIE
      - ZOMBIE_VILLAGER
      - SKELETON
      - CREEPER
      - SPIDER
      - WITCH
      - ENDERMAN
      - CAVE_SPIDER
      - SLIME
      - SILVERFISH
      - PIG_ZOMBIE
      - BLAZE
      - WITHER_SKELETON
      - MAGMA_CUBE
      - GHAST
      - STRAY
      - HUSK
      - DROWNED
      - PHANTOM
      - PILLAGER
      - RAVAGER
      - ILLUSIONER
      - VINDICATOR
      - EVOKER
      - VEX
      - VILLAGER
      - IRON_GOLEM
    MythicMobs-List-Enable: true
    MythicMobs-List: []

# Only support creatures.
# Entity type: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Spawn reason: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
#   Normal reason: NATURAL, SPAWNER, SPAWNER_EGG
#   Reason "CUSTOM" will not work if you have MythicMobs.
# Spawn biome: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html
# Spawn water: true or false. It will check if the spawn location in water or air.
# Spawn day: true or false. It will check if the world is day or night,
Spawn:
  PHANTOM:
    Chance: 0.3
    Reason: NATURAL
  BAT:
    Chance: 0.2
    Reason: NATURAL
  GUARDIAN:
    Chance: 0.01
    Reason: NATURAL
  SALMON:
    Chance: 0.2
    Reason: NATURAL
  PUFFERFISH:
    Chance: 0.2
    Reason: NATURAL
  TROPICAL_FISH:
    Chance: 0.2
    Reason: NATURAL

#  IRON_GOLEM:
#    Chance: 0.3
#    Reason: VILLAGE_DEFENSE
#  PIG_ZOMBIE:
#    Chance: 0.5
#    Reason: NETHER_PORTAL

# N#ormal example.
#  WOLF:
#    Chance: 0
#    Reason: NATURAL
#    Biome: DESERT
#    Water: true
#    Worlds:
#      - world
#      - world_nether
#
# Advanced example.
# You can set several condition groups and set it's own group name.
# More information: https://www.spigotmc.org/resources/entityplus.70592/
#  WOLF:
#    1:
#      Chance: 0
#      Reason: NATURAL
#      Biome: DESERT
#      Water: true
#      Worlds:
#        world:
#          X: 1000                # 1000 -> -1000 ~ 1000
#          Y: ">= 80"           # Support: >, <, =, >=, <=, ==
#          Z: "-1000 ~ 1000"
#    2:
#      Chance: 0
#      Reason: SPAWNER
#      Worlds:
#        world:
#          X: 1000
#          Z: 1000
#        world_nether: []
#    3:
#      Chance: 0
#      Reason: SPAWNER_EGG
#      Worlds:
#        world_the_end:
#          R: 1000

# The best way to change custom mobs spawn chance is in RandomSpawns.yml.
# MythicMobs: https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/
# Spawn "reason" doesn't work here.
MythicMobs-Spawn: []

MythicMobs-Drop:
  Enable: false
  # If player has multiple multipliers, he will get more rewards than the highest multiplier.
  # Calculation method: "+" or "*"
  Combined-Enable: true
  Combined-Method: "+"
  # You can add more multipliers. And the highest multiplier is the maximum number of group name.
  # Permission: "entityplus.drop.multiplier.GROUP"
  Multipliers:
    1:
      money: 1.5
      exp: 1.5
    2:
      money: 2
      exp: 2

Message:
  prefix: '&7[&dEntityPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'
  configReload: '&aConfiguration(s) Reloaded!'