# --{ =-=-=-=-=-=-=-=-=-= EntityPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
Config-Version: 7
Debugging: false
Check-Updates: true
Custom-Groups: true

General:
  # The searching players range from a location.
  Nearby-Players-Range: 32

# Control entities spawn and conditions.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Spawn
Spawn:
  Enable: false
  Settings:
    Features:
      # Control MythicMobs spawn and conditions.
      # MythicMobs: https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/
      # The "CUSTOM" reason does not work if you have MythicMobs.
      MythicMobs: true
      # More information: https://github.com/momoservertw/EntityPlus/wiki/Spawn#spawn-limit-example
      Limit:
        Enable: true
        AFK: true
        Residnece-Flag: true

# Control entities amount and save CPU performance.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Purge
Purge:
  Enable: false
  Check:
    Load: true
    Schedule:
      Enable: false
      Interval: 60
  Ignore:
    Named: true
    Tamed: true
    With-Saddle: true
    Baby-Animals: false
    Equipped: false
    Pickup-Equipped: true
    Reasons:
      - SPAWNER_EGG

# Change the reward for killing creatures.
# Support: KillerMoney, MythicMobs
Drop:
  Enable: false
  Settings:
    Affect-To-All-Creautes: true
    # Only change the rewards if the creature was killed by players.
    Has-Killer: true
    # If players has multiple groups, they will get all extra rewards.
    # Calculation method: "+" or "*"
    Combined:
      Enable: true
      Mode: "+"
  # Permission: "entityplus.drop.multiplier.GROUP"
  Groups:
    Lucky1:
      # The highest priority of group will be selected.
      Priority: 1
      # Give 150% money to player.
      # Need: KillerMoney and MythicMobs.
      Money: 1.5
      Exp: 1.5
      Items: 1.5
      # Change the reward for killing MythicMobs.
      # More information: https://github.com/momoservertw/EntityPlus/wiki/MythicMobs-Drop
      MythicMobs-Item: 1.5
    Lucky2:
      Priority: 2
      Money: 2
      Exp: 2
      Items: 2
      MythicMobs-Item: 1.5

# Skip the damage duration and then damage the creature immediately.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Damage-Skip-Duration
Damage-Skip-Duration:
  Enable: false
  # If the creature is close to the player, it will not kill creature or skip the duration of damage.
  No-Player-Range: 10
  Types:
    Fire:
      Enable: true
      Ignore-Sunburn: true
    Wither:
      Enable: true
    Poison:
      Enable: true
  Location:
    - world
    - world_nether
    - world_the_end
  # The list of creature type. If you set this option to "[]", it will affect to every creatures.
  # You can set the creature type from groups.yml. More information: https://github.com/momoservertw/EntityPlus/wiki/Custom-Groups
  List: []
  Ignore-List: []
  MythicMobs-List: []
  MythicMobs-Ignore-List: []

# Control creatures damage and modify it.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Damage
Damage:
  Enable: false
  Control:
    # Kill dying creatures directly and save CPU performance.
    Fast-Kill:
      Enable: true
      No-Player-Range: 10
      Action:
        Kill: true
      Reasons:
        - CRAMMING
        - DRYOUT
    Fast-Kill-HatFloor:
      Enable: true
      No-Player-Range: 10
      Action:
        Kill: true
      Reasons:
        - HOT_FLOOR
      Blocks:
        MAGMA_BLOCK:
          Offset: -1
          Ignore:
            Machines:
              Offset: 0
              List:
                - Item-Machines
    Fast-Kill-WitherRose:
      Enable: true
      No-Player-Range: 10
      Action:
        Kill: true
      Reasons:
        - WITHER
      Blocks:
        - WitherRose
    # It will prevent creature from dying if the creature is nearby the block end_portal.
    End-Portal-Duplicate:
      Enable: true
      Action:
        Damage: 0
      Blocks:
        END_PORTAL:
          Range:
            X: 3
            Y: 5
            Z: 3
      Location:
        - world
        - world_nether
      List:
        - ChestedHorse

# Change illegal spawners and randomly choose a new type, then execute custom commands.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Spawner
Spawner:
  Enable: false
  Settings:
    Features:
      Bypass:
        Residnece-Flag: true
  Control:
    Zombie:
      Enable: true
      Types:
        - ZOMBIE
        - SKELETON
      Location:
        - world
    Normal:
      Enable: true
      Location:
        - world
      # The type will not be changed.
      Allow-List:
        - ZOMBIE
        - SKELETON
        - SPIDER
        - CAVE_SPIDER
        - SILVERFISH
      # The type and chance of spawner will be changed.
      Change-List:
        SKELETON: 0.25
        ZOMBIE: 0.25
        SPIDER: 0.25
        CAVE_SPIDER: 0.25
      # It will execute commands when a spawner changed.
      # More information: https://github.com/momoservertw/EntityPlus/wiki/Custom-Commands
      Commands:
        - "log: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been changed to &e%spawner_newspawner%&c, nearby players: &e%spawner_nearbyplayers%"
        - "all-message: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been changed to &e%spawner_newspawner%&c."
    Nether:
      Enable: true
      Location:
        - world_nether
      Allow-List:
        - BLAZE
      Change-List:
        - BLAZE
      Commands:
        - "log: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been changed to &e%spawner_newspawner%&c, nearby players: &e%spawner_nearbyplayers%"
        - "all-message: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been changed to &e%spawner_newspawner%&c."
    Remove:
      Enable: true
      Remove: true
      Location:
        - world_the_end
      Commands:
        - "log: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been removed&c, nearby players: &e%spawner_nearbyplayers%"
        - "all-message: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been removed."

Message:
  prefix: '&7[&dEntityPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'
  configReload: '&aConfiguration(s) Reloaded!'
  unknownCommand: '&cUnknown command, See &e/entityplus help &cfor a list of commands.'
  EntityPlus:
    Commands:
      title: "&8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lEntityPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩"
      help: "&a/ep help &8- &7This help menu."
      reload: "&a/ep reload &8- &7Reloads config file."
      version: '&f/ep version &8- &7Checks the plugin version and updates.'