# ░░░░░░░░░░░░░░░   EntityPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/entityplus.70592/
#  Wiki: https://github.com/momoservertw/EntityPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 12
Debugging: false

# Controlling entities spawn, rewards, and damage.
# You need to add options in entities.yml.
Entities:
  Enable: false
  # Controlling entities spawn conditions.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Spawn
  Spawn:
    Settings:
      # Custom Residence flag "spawnbypass" to bypass the features.
      Residence-Flag: false
  # Limit the spawn amount and purge the exceeded mobs.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Spawn
  Limit:
    Enable: false
    Settings:
      # Custom Residence flag "entitylimitbypass" to bypass the features.
      Residence-Flag: false
      Purge:
        Enable: false
        Particle:
          Enable: true
          Type:
        Remove: true
        Check:
          Chunk-Radius: 3
          Player-Teleport: true
          Schedule:
            Enable: true
            Interval: 180
          Prevent:
            Gliding: true
            Flying: true
            Not-AFK: false
        Ignore:
          LiveTime-Under: 30
          Named: true
          Named-MythicMobs: false
          Tamed: true
          With-Saddle: true
          Pickup: true
          Baby-Animals: true
          # It will override the entities settings.
          List:
            - WITHER
            - Boss
    Groups:
      NormalMobs:
        Enable: true
        Amount: 10
        Chunk: 1
        Purge: true
        LiveTime-Over: 300
      BreedableMobs:
        Enable: true
        Chunk: 2
        Amount: 30
      WaterMobs:
        Enable: true
        Chunk: 2
        Amount: 5
  # Changing the reward for killing creatures.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Drop
  Drop:
    Enable: false
    Settings:
      Features:
        Bypass:
          # Custom Residence flag "dropbypass" to bypass the features.
          Residence-Flag: false
      # If players has multiple groups, they will get all extra rewards.
      # Mode: "none", "plus" or "multiply"
      Multiple-Groups: "none"
    # Permission: "entityplus.drop.GROUP"
    Groups:
      lucky1:
        Enable: true
        Priority: 1
        Exp: 1.5
        Items: 1.5
        Money: 1.5
        Commands: []
      lucky2:
        Enable: true
        Priority: 2
        Exp: 2
        Items: 2
        Money: 2
        Commands: []
  # Skipping the damage duration and damaging the creature immediately.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Damage
  Damage:
    Enable: false
    Settings:
      Features:
        Bypass:
          # Custom Residence flag "damagebypass" to bypass the features.
          Residence-Flag: false
    Groups:
      Skip-Duration:
        Enable: true
        Reasons:
          - FIRE_TICK
          - WITHER
          - POISON
        Action:
          Skip-Duration: true
        Ignore:
          Player-Nearby-Range: 10
          Sunburn: true
      Fast-Kill:
        Enable: true
        Reasons:
          - CRAMMING
          - DRYOUT
        Action:
          Kill: true
        Ignore:
          Player-Nearby-Range: 10
      Fast-Kill-WitherRose:
        Enable: true
        Reasons:
          - WITHER
        Blocks:
          - InWitherRose
        Action:
          Kill: true
        Ignore:
          Player-Nearby-Range: 10

# Change the illegal spawner and randomly select a new type for it, and then execute the custom command.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Spawner
Spawner:
  Enable: false
  Settings:
    Message:
      Log: true
      Console: true
      Nearby-Players: true
    # Sending commands nearby players. Set "0" to disable checking.
    Nearby-Players-Range: 32
    Bypass:
      # Custom Residence flag "spawnerbypass" to bypass the features.
      Residence-Flag: false
  Groups:
    Normal:
      Enable: true
      Location:
        - world
      Blocks: []
      Allow-Types:
        - ZOMBIE
        - SKELETON
        - SPIDER
        - CAVE_SPIDER
        - SILVERFISH
      Change-Types:
        SKELETON: 1
        ZOMBIE: 1
        SPIDER: 1
        CAVE_SPIDER: 1
      Commands:
        - "log-custom: SpawnerChanged, %entity_display_name% spawner - %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%, nearby players: %nearbyplayers%"
        - "print: &c%entity_display_name% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%, nearby players: %nearbyplayers%"
        - "targets-message: &c%entity_display_name% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%."
    Nether:
      Enable: true
      Location:
        - world_nether
      Allow-Types:
        - BLAZE
      Change-Types:
        - BLAZE
      Commands:
        - "log-custom: SpawnerChanged, %spawner% spawner - %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%, nearby players: %nearbyplayers%"
        - "print: &c%spawner% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%, nearby players: %nearbyplayers%"
        - "targets-message: &c%spawner% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%."
    Remove:
      Enable: true
      Remove: true
      Location:
        - world_the_end
      Commands:
        - "log-custom: SpawnerChanged, %spawner% spawner - %world%(%loc_x%, %loc_y%, %loc_z%) has been removed, nearby players: %nearbyplayers%"
        - "print: &c%spawner% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been removed, nearby players: %nearbyplayers%"
        - "targets-message: &c%spawner% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been removed."

Message:
  prefix: '&7[&dEntityPlus&7]&r '
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩ &d&lEntityPlus &8▩▩▩▩▩▩▩▩▩▩"
    help: "&a/ep help &8- &7This help menu."
    reload: "&a/ep reload &8- &7Reloads config file."
    version: '&f/ep version &8- &7Checks the plugin version and updates.'