# ░░░░░░░░░░░░░░░   EntityPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/entityplus.70592/
#  Wiki: https://github.com/momoservertw/EntityPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 12
Debugging: false

# Controlling entities spawn conditions, rewards, and damage.
Entities:
  # Controlling entities spawn conditions.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Spawn
  Spawn:
    Enable: false
    Settings:
      Features:
        Bypass:
          # Custom Residence flag "spawnbypass" to bypass the features.
          # Changing this option requires restarting the server.
          Residence-Flag: false
    # Limit the range of monsters around the player to avoid unnecessary monsters.
    Range:
      Enable: false
      # You need to add an option "range: GroupName" in entities.yml.
      Groups:
        Default:
          Enable: true
          # Extend more chunks to allow spawn mobs. Based on the value of the option "mob-spawn-range" in Spigot.yml.
          Extend: 0
          # Prevent spawn monsters when all player nearby is using elytra.
          Cancel-Gliding: true
          Cancel-Flying: true
        Near:
          Enable: true
          # Unit: block
          Block: 48
        Boss:
          Enable: true
          Extend: 0
          Cancel-Gliding: true
          Cancel-Flying: true
          Permission: "entityplus.spawn.mobs.boss"
    # Prevent spawning new creatures if there are too many creatures nearby the location.
    Limit:
      Enable: false
      Settings:
        Features:
          AFK: false
      # You need to add an option in entities.yml.
      Groups:
        NormalMobs:
          Enable: true
          Amount: 10
          Chance: 0
          AFK:
            Enable: false
            Chance: 0
            Amount: 5
          Search:
            X: 8
            Z: 8
            Y: 5
        BreedableMobs:
          Enable: true
          Amount: 20
          Chance: 0
          Search:
            X: 16
            Z: 16
            Y: 10
        WaterMobs:
          Enable: true
          Amount: 10
          Chance: 0
          Search:
            X: 16
            Z: 16
            Y: 10
  # Changing the reward for killing creatures.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Drop
  Drop:
    Enable: false
    Settings:
      Features:
        Exp: true
        Items: true
        MythicMobs:
          Money: true
        Bypass:
          # Custom Residence flag "dropbypass" to bypass the features.
          # Changing this option requires restarting the server.
          Residence-Flag: false
      # If players has multiple groups, they will get all extra rewards.
      # Mode: "plus" or "multiply"
      Bonus:
        Enable: true
        Mode: "plus"
    # Permission: "entityplus.drop.GROUP"
    Groups:
      lucky1:
        Enable: true
        Priority: 1
        Exp: 1.5
        Items: 1.5
        Money: 1.5
        # Available type: Vanilla, Custom Group, MythicMobs
        Types:
          - NormalMobs
      lucky2:
        Enable: true
        Priority: 2
        Exp: 2
        Items: 2
        Money: 2
        Types:
          - NormalMobs
  # Skipping the damage duration and damaging the creature immediately.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Damage
  Damage:
    Enable: false
    Settings:
      Features:
        Bypass:
          # Custom Residence flag "damagebypass" to bypass the features.
          # Changing this option requires restarting the server.
          Residence-Flag: false
    Groups:
      Skip-Duration:
        Enable: true
        Priority: 2
        Types:
          - NormalMobs
        Reasons:
          - FIRE_TICK
          - WITHER
          - POISON
        Action:
          Skip-Duration: true
        Ignore:
          Player-Nearby-Range: 10
          Sunburn: true
      Fast-Kill:
        Enable: true
        Priority: 2
        Types:
          - NormalMobs
        Reasons:
          - CRAMMING
          - DRYOUT
        Action:
          Kill: true
        Ignore:
          Player-Nearby-Range: 10
      Fast-Kill-WitherRose:
        Enable: true
        Priority: 2
        Types:
          - NormalMobs
        Reasons:
          - WITHER
        Blocks:
          - InWitherRose
        Action:
          Kill: true
        Ignore:
          Player-Nearby-Range: 10

# Change the illegal spawner and randomly select a new type for it, and then execute the custom command.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Spawner
Spawner:
  Enable: false
  Settings:
    Message:
      Log: true
      Console: true
      Nearby-Players: true
    # Sending commands nearby players. Set "0" to disable checking.
    Nearby-Players-Range: 32
    Bypass:
      # Custom Residence flag "spawnerbypass" to bypass the features.
      # Changing this option requires restarting the server.
      Residence-Flag: false
  Groups:
    Normal:
      Enable: true
      Location:
        - world
      Blocks: []
      Allow-Types:
        - ZOMBIE
        - SKELETON
        - SPIDER
        - CAVE_SPIDER
        - SILVERFISH
      Change-Types:
        SKELETON: 1
        ZOMBIE: 1
        SPIDER: 1
        CAVE_SPIDER: 1
      Commands:
        - "log-custom: SpawnerChanged, %entity_display_name% spawner - %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%, nearby players: %nearbyplayers%"
        - "print: &c%entity_display_name% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%, nearby players: %nearbyplayers%"
        - "targets-message: &c%entity_display_name% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%."
    Nether:
      Enable: true
      Location:
        - world_nether
      Allow-Types:
        - BLAZE
      Change-Types:
        - BLAZE
      Commands:
        - "log-custom: SpawnerChanged, %spawner% spawner - %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%, nearby players: %nearbyplayers%"
        - "print: &c%spawner% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%, nearby players: %nearbyplayers%"
        - "targets-message: &c%spawner% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been changed to %new_spawner%."
    Remove:
      Enable: true
      Remove: true
      Location:
        - world_the_end
      Commands:
        - "log-custom: SpawnerChanged, %spawner% spawner - %world%(%loc_x%, %loc_y%, %loc_z%) has been removed, nearby players: %nearbyplayers%"
        - "print: &c%spawner% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been removed, nearby players: %nearbyplayers%"
        - "targets-message: &c%spawner% spawner at %world%(%loc_x%, %loc_y%, %loc_z%) has been removed."

Message:
  prefix: '&7[&dEntityPlus&7]&r '
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩ &d&lEntityPlus &8▩▩▩▩▩▩▩▩▩▩"
    help: "&a/ep help &8- &7This help menu."
    reload: "&a/ep reload &8- &7Reloads config file."
    version: '&f/ep version &8- &7Checks the plugin version and updates.'