# --{ =-=-=-=-=-=-=-=-=-= EntityPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
Config-Version: 10
Check-Updates: true
Debugging: false

General:
  # The searching players range from a location.
  Nearby-Players-Range: 32

Entities:
  Spawn:
    Enable: false
    Settings:
      Features:
        # Control MythicMobs spawn and conditions.
        # The "CUSTOM" reason does not work if you have MythicMobs.
        # MythicMobs: https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/
        MythicMobs: true
        Bypass:
          Residence-Flag: false
  # If there are too many creatures over the spawn location, it will prevent spawning creatures.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Limit
  Limit:
    Enable: false
    Settings:
      Features:
        AFK: true
        Bypass:
          Residence-Flag: false
    Groups:
      NormalMobs:
        Enable: true
        Chance: 0
        Amount: 10
        AFK:
          Enable: false
          Amount: 5
          Chance: 0
        Search:
          X: 8
          Z: 8
          Y: 5
      BreedableMobs:
        Enable: false
        Chance: 0
        Amount: 20
        Search:
          X: 16
          Z: 16
          Y: 10
      WaterMobs:
        Enable: false
        Chance: 0
        Amount: 10
        Search:
          X: 16
          Z: 16
          Y: 10
  # Change the reward for killing creatures.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Drop
  Drop:
    Enable: false
    Settings:
      Features:
        Money: true
        Exp: true
        Items: true
        MythicMobs-Items: true
        Bypass:
          Residence-Flag: false
      # If players has multiple groups, they will get all extra rewards.
      # Mode: "plus" or "multiply"
      Bonus:
        Enable: true
        Mode: "plus"
    # Permission: "entityplus.drop.multiplier.GROUP"
    Groups:
      lucky1:
        Enable: true
        # The highest priority of group will be selected.
        Priority: 1
        # Give 150% money to player. Need: MythicMobs.
        Money: 1.5
        Exp: 1.5
        Items: 1.5
        # Change the reward for killing MythicMobs.
        MythicMobs-Items: 1.5
      lucky2:
        Enable: true
        Priority: 2
        Money: 2
        Exp: 2
        Items: 2
        MythicMobs-Items: 1.5
  # Control creatures damage and modify it.
  # More information: https://github.com/momoservertw/EntityPlus/wiki/Damage
  Damage:
    Enable: false
    Groups:
      # Kill dying creatures directly and save CPU performance.
      Fast-Kill:
        Enable: true
        No-Player-Range: 10
        Action:
          Kill: true
        Reasons:
          - CRAMMING
          - DRYOUT
      Fast-Kill-HatFloor:
        Enable: true
        No-Player-Range: 10
        Action:
          Kill: true
        Reasons:
          - HOT_FLOOR
        Blocks:
          MAGMA_BLOCK:
            Offset: -1
            Ignore:
              Machines:
                Offset: 0
                List:
                  - Item-Machines
      Fast-Kill-WitherRose:
        Enable: true
        No-Player-Range: 10
        Action:
          Kill: true
        Reasons:
          - WITHER
        Blocks:
          - WitherRose
      # It will prevent creature from dying if the creature is nearby the block end_portal.
      End-Portal-Duplicate:
        Enable: true
        Action:
          Damage: 0
        Blocks:
          END_PORTAL:
            Range:
              X: 3
              Y: 5
              Z: 3
        Location:
          - world
          - world_nether
        List:
          - ChestedHorse

# Skip the damage duration and then damage the creature immediately.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Damage-Skip-Duration
Damage-Skip-Duration:
  Enable: false
  Settings:
    # If the creature is close to the player, it will not kill creature or skip the duration of damage.
    No-Player-Range: 10
  Groups:
    Fire:
      Enable: true
      Ignore-Sunburn: true
    Wither:
      Enable: true
    Poison:
      Enable: true
  Location:
    - world
    - world_nether
    - world_the_end
  # The list of creature type. If you set this option to "[]", it will affect to every creatures.
  # You can set the creature type from groups.yml. More information: https://github.com/momoservertw/EntityPlus/wiki/Custom-Groups
  List: []
  Ignore-List: []
  MythicMobs-List: []
  MythicMobs-Ignore-List: []

# Control entities amount and save CPU performance.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Purge
Purge:
  Enable: false
  Settings:
    # The checking range of chunks.
    Range: 2
    Check:
      Load: true
      Schedule:
        Enable: false
        Interval: 60
    Ignore:
      Named: true
      Tamed: true
      With-Saddle: true
      Baby-Animals: false
      Equipped: false
      Pickup-Equipped: true
      Reasons:
        - SPAWNER_EGG
  Groups:
    NormalMobs:
      Enable: true
      List:
        - NormalMobs
      Amount: 10

# Change the illegal spawner and randomly select a new type for it, and then execute the custom command.
# More information: https://github.com/momoservertw/EntityPlus/wiki/Spawner
Spawner:
  Enable: false
  Settings:
    Bypass:
      Residence-Flag: true
  Groups:
    Normal:
      Enable: true
      Location:
        - world
      Blocks: []
      Allow-Types:
        - ZOMBIE
        - SKELETON
        - SPIDER
        - CAVE_SPIDER
        - SILVERFISH
      Change-Types:
        SKELETON: 1
        ZOMBIE: 1
        SPIDER: 1
        CAVE_SPIDER: 1
      Commands:
        - "log: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been changed to &e%spawner_newspawner%&c, nearby players: &e%spawner_nearbyplayers%"
        - "all-message: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been changed to &e%spawner_newspawner%&c."
    Nether:
      Enable: true
      Location:
        - world_nether
      Allow-Types:
        - BLAZE
      Change-Types:
        - BLAZE
      Commands:
        - "log: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been changed to &e%spawner_newspawner%&c, nearby players: &e%spawner_nearbyplayers%"
        - "all-message: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been changed to &e%spawner_newspawner%&c."
    Remove:
      Enable: true
      Remove: true
      Location:
        - world_the_end
      Commands:
        - "log: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been removed&c, nearby players: &e%spawner_nearbyplayers%"
        - "all-message: &e%spawner_type% spawner &cat %spawner_world%(%spawner_loc_x%, %spawner_loc_y%, %spawner_loc_z%) has been removed."

Message:
  prefix: '&7[&dEntityPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'
  configReload: '&aConfiguration(s) Reloaded!'
  unknownCommand: '&cUnknown command, See &e/entityplus help &cfor a list of commands.'
  EntityPlus:
    Commands:
      title: "&8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩ &d&lEntityPlus &8▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩"
      help: "&a/ep help &8- &7This help menu."
      reload: "&a/ep reload &8- &7Reloads config file."
      version: '&f/ep version &8- &7Checks the plugin version and updates.'