# --{ =-=-=-=-=-=-=-=-=-= EntityPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
config-Version: 3
Metrics-Logging: true
Log-Coloration: true

# If there are too many entities over there the spawn location, it will cancel the spawn event.
# You can add  the flag "Limit: false" in spawn list to bypass the spawn limit.
Spawn-Limit-Flag:
  Default: true
  Max-Amount: 5
  Range:
    X: 8
    Y: 5
    Z: 8

# Entity type: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Spawn reason: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
#   Normal reason: NATURAL, SPAWNER, SPAWNER_EGG
#   Reason "CUSTOM" will not work if you have MythicMobs.
# Spawn biome: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html
# Spawn water: true or false. It will check if the spawn location in water or air.
# Spawn limit: false. The entity will bypass the spawn maximum amount.
Spawn:
  PHANTOM:
    Chance: 0.3
  BAT:
    Chance: 0.2
  GUARDIAN:
    Chance: 0.01
  SALMON:
    Chance: 0.2
    Reason: NATURAL
  PUFFERFISH:
    Chance: 0.2
    Reason: NATURAL
  TROPICAL_FISH:
    Chance: 0.2
    Reason: NATURAL
  Wolf:
    1:
      Chance: 0
      Reason: NATURAL
      Biome: DESERT
      Water: true
      Limit: false
      Worlds:
        world:
          X: "1000"
          Y: ">= 80"
          Z: "-1000 ~ 1000"
    2:
      Chance: 0
      Reason: SPAWNER
      Worlds:
        world:
          X: "1000"
          Z: "1000"
        world_nether: []

#  IRON_GOLEM:
#    Chance: 0.3
#    Reason: VILLAGE_DEFENSE
#  PIG_ZOMBIE:
#    Chance: 0.5
#    Reason: NETHER_PORTAL

# Normal example.
#  Wolf:
#    Chance: 0
#    Reason: NATURAL
#    Biome: DESERT
#    Water: true
#    Limit: false
#    Worlds:
#      - world
#      - world_nether
#
# Advanced example.
# You can set several condition groups and set it's own group name.
# More information: https://www.spigotmc.org/resources/entityplus.70592/
#  Wolf:
#    1:
#      Chance: 0
#      Reason: NATURAL
#      Biome: DESERT
#      Water: true
#      Limit: false
#      Worlds:
#        world:
#          X: "1000"            # "1000" -> -1000 ~ 1000
#          Y: ">= 80"           # Support: >, <, =, >=, <=, ==
#          Z: "-1000 ~ 1000"
#    2:
#      Chance: 0
#      Reason: SPAWNER
#      Worlds:
#        world:
#          X: "1000"
#          Z: "1000"
#        world_nether: []

# The best way to change custom mobs spawn chance is in RandomSpawns.yml.
# MythicMobs: https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/
# Spawn "reason" doesn't work here.
MythicMobs-Spawn: []

MythicMobs-Drop:
  Enable: true
  # If player has multiple multipliers, he will get more rewards than just the highest multiplier.
  # Calculation method: addition or multiplication
  Combined-enable: true
  Combined-method: addition
  # You can add more multipliers.
  # Permission: "entityplus.drop.multiplier.GROUP"
  Multipliers:
    1:
      money: 1.5
      exp: 1.5
    2:
      money: 2
      exp: 2

Message:
  prefix: '&7[&dEntityPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'