# --{ =-=-=-=-=-=-=-=-=-= EntityPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
config-Version: 3
Metrics-Logging: true
Log-Coloration: true

# Entity type: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Spawn reason: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
#   Normal reason: NATURAL, SPAWNER, SPAWNER_EGG
#   Reason "CUSTOM" will not work if you have MythicMobs.
# Spawn biome: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html
# Spawn water: true or false. It will check if the spawn location in water or air.
Spawn:
  PHANTOM:
    Chance: 0.3
  BAT:
    Chance: 0.2
  GUARDIAN:
    Chance: 0.01
  IRON_GOLEM:
    Chance: 0.3
    Reason: VILLAGE_DEFENSE
  SALMON:
    Chance: 0.2
    Reason: NATURAL
  PUFFERFISH:
    Chance: 0.2
    Reason: NATURAL
  TROPICAL_FISH:
    Chance: 0.2
    Reason: NATURAL
#  PIG_ZOMBIE:
#    Reason: NETHER_PORTAL
#    Chance: 0.5

# Normal example.
#  Wolf:
#    Chance: 0
#    Reason: NATURAL
#    Biome: DESERT
#    Water: true
#    Worlds:
#      - world
#      - world_nether
#
# Coordinate format: X, Y, Z, !X, !Y, etc ...
# Range format: "1000", ">= 80", "-1000 ~ 1000"
# More information: https://www.spigotmc.org/resources/entityplus.70592/
# Advanced example.
#  Wolf:
#    1:
#      Chance: 0
#      Reason: NATURAL
#      Biome: DESERT
#      Water: true
#      Worlds:
#        # X: "1000" -> -1000 ~ 1000
#        # Y: ">= 80" -> Support: >, <, =, >=, <=, ==
#        world:
#          X: "1000"
#          Y: ">= 80"
#          Z: "-1000 ~ 1000"
#    2:
#      Chance: 0
#      Reason: SPAWNER
#      Worlds:
#        world:
#          XZ: "1000"
#        world_nether: []

# You can change MythicMobs spawn chance here.
# The best way to change custom mobs spawn chance is in RandomSpawns.yml, but for some reason you may need it.
# MythicMobs: https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/
# Spawn reason will not work in "MythicMobs-Spawn".
MythicMobs-Spawn: []

MythicMobs-Drop:
  Enable: true
  # If player has multiple multipliers, he will get more rewards than just the highest multiplier.
  # Calculation method: addition or multiplication
  Combined-enable: true
  Combined-method: addition
  # You can add more multipliers.
  # Permission: "entityplus.drop.multiplier.GROUP"
  Multipliers:
    1:
      money: 1.5
      exp: 1.5
    2:
      money: 2
      exp: 2

Message:
  prefix: '&7[&dEntityPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'