# --{ =-=-=-=-=-=-=-=-=-= EntityPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
config-Version: 2
Metrics-Logging: true
Log-Coloration: true

# Entity type: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Normal reason: NATURAL, SPAWNER, CUSTOM
# CUSTOM: hen a creature is spawned by plugins.
# Spawn reason: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
# Spawn biome: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html
# Spawn in water: true
# Spawn location example: "X: -1000 ~ 1000", "X: >= 1000"
Spawn:
  PHANTOM:
    Chance: 0.3
  BAT:
    Chance: 0.2
  GUARDIAN:
    Chance: 0.01
  IRON_GOLEM:
    Chance: 0.3
    Reason: VILLAGE_DEFENSE
  SALMON:
    Chance: 0.2
    Reason: NATURAL
  PUFFERFISH:
    Chance: 0.2
    Reason: NATURAL
  TROPICAL_FISH:
    Chance: 0.2
    Reason: NATURAL

  CAVE_SPIDER:
    1:
      Chance: 0
      Reason: SPAWNER
      Biome: DESERT
      Water: true
      World:
        test:
          X: "1000"
          Y: "> 80"
          Z: "-1000 ~ 1000"
    2:
      Chance: 0
      Reason: SPAWNER
      Biome: DESERT
      Water: true
      World:
        test:
          X: "-1000 ~ 1000"
          Y: "> 80"
          Z: "-1000 ~ 1000"

#  PIG_ZOMBIE:
#    Reason: NETHER_PORTAL
#    Chance: 0.5

# Normal example:
#  CAVE_SPIDER:
#    Chance: 0
#    Reason: SPAWNER
#    Biome: DESERT
#    Water: false
#    Location:
#    World: test
#    X: -1000 ~ 1000
#    Y: 80 >
#    Z: -1000 ~ 1000

# Advanced example:
#  CAVE_SPIDER:
#    First:
#      Chance: 0
#      Reason: SPAWNER
#      Biome: DESERT
#      Water: false
#      Location:
#        World: test
#        X: "1000"                       # X = -1000 ~ 1000
#        Y: ">= 80"                     # Support ">, <, =, >=, <=, =="
#        Z: "-1000 ~ 1000"
#    Second:
#      Chance: 0.1
#      Biome: DESERT
#    Third:
#      Chance: 0.8

# You can change MythicMobs spawn chance here.
# The best way to change custom mobs spawn chance is in RandomSpawns.yml, but for some reason you may need it.
# MythicMobs: https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/
MythicSpawn:
  Crazy_Zombie:
    Chance: 0.1
  Crazy_Player:
    Chance: 0
    Water: false

MythicMobs-Drop:
  Enable: true
  # If player has multiple multipliers, he will get more rewards than just the highest multiplier.
  # Calculation method: addition or multiplication
  Combined-enable: true
  Combined-method: addition
  # You can add more multipliers.
  # Permission: "entityplus.drop.multiplier.GROUP"
  Multipliers:
    1:
      money: 1.5
      exp: 1.5
    2:
      money: 2
      exp: 2

Message:
  prefix: '&7[&dEntityPlus&7]&r '
  noPermission: '&cYou do not have permission to use that command!'