# --{ =-=-=-=-=-=-=-=-=-= EntityPlus's Configuration Settings, by Momocraft =-=-=-=-=-=-=-=-=-= }--
config-Version: 1
Metrics-Logging: true
Log-Coloration: true

# How many percent of mobs will spawn. You can add a new one you want.
#Entity type can find here.
#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
Mobs-Spawn-Chance:
  GUARDIAN: 0.1
  IRON_GOLEM: 0.5

Message:
  Prefix: '&7[&dEntityPlus&7]&r '
  Commands:
    noPermission: '&cYou do not have permission to use that command!'