name: EntityPlus
main: tw.momocraft.entityplus.EntityPlus
author: Momocraft
api-version: 1.13
version: 1.2.0
description: Control creatures spawn and spawner. And add more features for MythicMobs and CMI.
softdepend: [Vault, MythicMobs, CMI, Residence, PlaceHolderAPI]

commands:
  entityplus:
    description: Displays main command menu.
    permission: entityplus.use
    aliases: [ep]
    usage: |
      /entityplus

permissions:
  entityplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      entityplus.use: true
      entityplus.command.*: true
      entityplus.bypass.*: true
      entityplus.drop.*: true
  entityplus.use:
    description: Allows use of basic commands.
    default: true
  entityplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      entityplus.command.reload: true
      entityplus.command.version: true
  entityplus.command.reload:
    description: Allows use of /entityplus command reload.
    default: op
  entityplus.command.version:
    description: Allows use of command /barrierplus version.
    default: op
  entityplus.bypass.*:
    description: Bypass the spawn amount limit when player is afk.
    default: op
    children:
      entityplus.bypass.spawnlimit.afk: true
      entityplus.bypass.purge.afk: true
  entityplus.bypass.spawnlimit.afk:
    description: Bypass the spawn amount limit when player is afk.
    default: op
  entityplus.bypass.purge.afk:
    description: Bypass the purge event when player is afk.
    default: op
  entityplus.drop.*:
    description: Get multiple "money" and "exp" after player killing a mob.
    default: op
    children:
      entityplus.drop.multiplier.*: true
  entityplus.drop.multiplier.*:
    description: Get multiple "money" and "exp" after player killing a mob.
    default: op
    children:
      entityplus.drop.multiplier.1: true
      entityplus.drop.multiplier.2: true
  entityplus.drop.multiplier.1:
    description: Get multiple "money" and "exp" after player killing a mob.
    default: op
  entityplus.drop.multiplier.2:
    description: Get multiple "money" and "exp" after player killing a mob.
    default: op