name: EntityPlus
main: tw.momocraft.entityplus.EntityPlus
author: Momocraft
api-version: 1.13
version: 1.1.4
description: Control entities.
softdepend: [Vault, MythicMobs, CMI, Residence, PlaceHolderAPI]

commands:
  entityplus:
    description: Displays main command menu.
    permission: entityplus.use
    usage: |
      /entityplus
  entityplus reload:
    description: Reloads all EntityPlus configuration files and caches any new data.
    permission: entityplus.command.reload
    usage: |
        /entityplus reload

permissions:
  entityplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      entityplus.use: true
      entityplus.command.*: true
      entityplus.bypass.*: true
  entityplus.use:
    description: Allows use of basic commands.
    default: true
  entityplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      entityplus.command.reload: true
  entityplus.command.reload:
    description: Allows use of /entityplus command reload.
    default: op
  entityplus.bypass.*:
    description: Bypass the spawn amount limit when player is afk.
    default: op
    children:
      entityplus.bypass.spawnlimit.afk: true
      entityplus.bypass.purge.afk: true
  entityplus.bypass.spawnlimit.afk:
    description: Bypass the spawn amount limit when player is afk.
    default: op
  entityplus.bypass.purge.afk:
    description: Bypass the purge event when player is afk.
    default: op
  entityplus.drop:
    description: Bypass the purge event when player is afk.
    default: op