name: EntityPlus
main: tw.momocraft.entityplus.EntityPlus
author: Momocraft
api-version: 1.14
version: 1.0-SNAPSHOT
description: To change Guardian's spawn chance

commands:
  entityplus:
    description: Displays main command menu.
    permission: entityplus.use
    usage: |
      /entityplus

permissions:
  entityplus.*:
    description: Allows use of all commands and feature.
    default: op
  entityplus.all:
    description: Allows use of all commands and feature.
    default: op
    children:
      entityplus.use: true
  entityplus.use:
    description: Allows use of basic commands.
    default: true