name: EntityPlus
main: tw.momocraft.entityplus.EntityPlus
author: Momocraft
api-version: 1.13
version: 1.2.3
description: Control entities.
softdepend: [Vault, MythicMobs, CMI, Residence, PlaceHolderAPI]

commands:
  entityplus:
    description: Displays main command menu.
    permission: entityplus.use
    aliases: [ep]
    usage: |
      /entityplus

permissions:
  entityplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      entityplus.use: true
      entityplus.command.*: true
      entityplus.bypass.*: true
      entityplus.drop.*: true
  entityplus.use:
    description: Allows use of basic commands.
    default: true
  entityplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      entityplus.command.reload: true
      entityplus.command.version: true
  entityplus.command.reload:
    description: Allows use of /entityplus command reload.
    default: op
  entityplus.command.version:
    description: Allows use of command /entityplus version.
    default: op
  entityplus.bypass.*:
    description: Bypass all limits.
    default: op
    children:
      entityplus.bypass.spawnlimit.afk: true
  entityplus.bypass.spawnlimit.afk:
    description: Bypass the spawn amount limit when player is AFK.
    default: op
  entityplus.drop.*:
    description: Change the reward for killing creatures.
    default: op
    children:
      entityplus.drop.lucky1: true
      entityplus.drop.lucky2: true
  entityplus.drop.lucky1:
    description: Change the reward for killing creatures.
    default: op
  entityplus.drop.multiplier.lucky2:
    description: Change the reward for killing creatures.
    default: op